//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 30.06.2021 16:53:17
namespace Com.Sap.Gateway.Srvd_a2x.Zui_s4crm_sr_zral.V0001
{
        /// <summary>
        /// There are no comments for Container in the schema.
        /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot) :
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "com.sap.gateway.srvd_a2x.zui_s4crm_sr_zral.v0001", "Com.Sap.Gateway.Srvd_a2x.Zui_s4crm_sr_zral.V0001");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("Com.Sap.Gateway.Srvd_a2x.Zui_s4crm_sr_zral.V0001", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("com.sap.gateway.srvd_a2x.zui_s4crm_sr_zral.v0001.", originalNameAttribute.OriginalName);
                }
                return string.Concat("com.sap.gateway.srvd_a2x.zui_s4crm_sr_zral.v0001.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Issue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Issue")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<IssueType> Issue
        {
            get
            {
                if ((this._Issue == null))
                {
                    this._Issue = base.CreateQuery<IssueType>("Issue");
                }
                return this._Issue;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<IssueType> _Issue;
        /// <summary>
        /// There are no comments for Issue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToIssue(IssueType issueType)
        {
            base.AddObject("Issue", issueType);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private const string filePath = @"IssueServiceCsdl.xml";

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader();
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;

                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, true, out edmModel, out errors))
                    {
	                    global::System.Text.StringBuilder errorMessages = new global::System.Text.StringBuilder();
	                    foreach (var error in errors)
	                    {
		                    errorMessages.Append(error.ErrorMessage);
		                    errorMessages.Append("; ");
	                    }
	                    throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader()
            {
                try
                {
                    var assembly = global::System.Reflection.Assembly.GetExecutingAssembly();
                    var resourcePath = global::System.Linq.Enumerable.Single(assembly.GetManifestResourceNames(), str => str.EndsWith(filePath));
                    global::System.IO.Stream stream = assembly.GetManifestResourceStream(resourcePath);
                    return global::System.Xml.XmlReader.Create(new global::System.IO.StreamReader(stream));
                }
                catch(global::System.Xml.XmlException e)
                {
                    throw new global::System.Xml.XmlException("Failed to create an XmlReader from the stream. Check if the resource exists.", e);
                }
            }
        }
    }
        /// <summary>
        /// There are no comments for IssueTypeSingle in the schema.
        /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("IssueTypeSingle")]
    public partial class IssueTypeSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<IssueType>
    {
        /// <summary>
        /// Initialize a new IssueTypeSingle object.
        /// </summary>
        public IssueTypeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new IssueTypeSingle object.
        /// </summary>
        public IssueTypeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new IssueTypeSingle object.
        /// </summary>
        public IssueTypeSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<IssueType> query)
            : base(query) {}

    }
        /// <summary>
        /// There are no comments for IssueType in the schema.
        /// </summary>
    /// <KeyProperties>
    /// ServiceIssue
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("ServiceIssue")]
    [global::Microsoft.OData.Client.EntitySet("Issue")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("IssueType")]
    public partial class IssueType : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new IssueType object.
        /// </summary>
        /// <param name="serviceIssue">Initial value of ServiceIssue.</param>
        /// <param name="priority">Initial value of Priority.</param>
        /// <param name="priorityText">Initial value of PriorityText.</param>
        /// <param name="description">Initial value of Description.</param>
        /// <param name="responsibleEmployee">Initial value of ResponsibleEmployee.</param>
        /// <param name="respEmployeeFullName">Initial value of RespEmployeeFullName.</param>
        /// <param name="status">Initial value of Status.</param>
        /// <param name="statusCriticality">Initial value of StatusCriticality.</param>
        /// <param name="statusText">Initial value of StatusText.</param>
        /// <param name="businessActivityCategory">Initial value of BusinessActivityCategory.</param>
        /// <param name="entryChannel">Initial value of EntryChannel.</param>
        /// <param name="serviceDefectSchema">Initial value of ServiceDefectSchema.</param>
        /// <param name="serviceDefectCategory">Initial value of ServiceDefectCategory.</param>
        /// <param name="serviceDefectCodeText">Initial value of ServiceDefectCodeText.</param>
        /// <param name="serviceReasonSchema">Initial value of ServiceReasonSchema.</param>
        /// <param name="serviceReasonCategory">Initial value of ServiceReasonCategory.</param>
        /// <param name="serviceReasonCodeText">Initial value of ServiceReasonCodeText.</param>
        /// <param name="processingTimeInHours">Initial value of ProcessingTimeInHours.</param>
        /// <param name="owner">Initial value of Owner.</param>
        /// <param name="ownerFullName">Initial value of OwnerFullName.</param>
        /// <param name="billToParty">Initial value of BillToParty.</param>
        /// <param name="reportedBy">Initial value of ReportedBy.</param>
        /// <param name="reportedByFullName">Initial value of ReportedByFullName.</param>
        /// <param name="shipToParty">Initial value of ShipToParty.</param>
        /// <param name="buildingCustodian">Initial value of BuildingCustodian.</param>
        /// <param name="custodianFullName">Initial value of CustodianFullName.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static IssueType CreateIssueType(string serviceIssue, 
                    string priority, 
                    string priorityText, 
                    string description, 
                    string responsibleEmployee, 
                    string respEmployeeFullName, 
                    string status, 
                    byte statusCriticality, 
                    string statusText, 
                    string businessActivityCategory, 
                    string entryChannel, 
                    string serviceDefectSchema, 
                    string serviceDefectCategory, 
                    string serviceDefectCodeText, 
                    string serviceReasonSchema, 
                    string serviceReasonCategory, 
                    string serviceReasonCodeText, 
                    decimal processingTimeInHours, 
                    string owner, 
                    string ownerFullName, 
                    string billToParty, 
                    string reportedBy, 
                    string reportedByFullName, 
                    string shipToParty, 
                    string buildingCustodian, 
                    string custodianFullName)
        {
            IssueType issueType = new IssueType();
            issueType.ServiceIssue = serviceIssue;
            issueType.Priority = priority;
            issueType.PriorityText = priorityText;
            issueType.Description = description;
            issueType.ResponsibleEmployee = responsibleEmployee;
            issueType.RespEmployeeFullName = respEmployeeFullName;
            issueType.Status = status;
            issueType.StatusCriticality = statusCriticality;
            issueType.StatusText = statusText;
            issueType.BusinessActivityCategory = businessActivityCategory;
            issueType.EntryChannel = entryChannel;
            issueType.ServiceDefectSchema = serviceDefectSchema;
            issueType.ServiceDefectCategory = serviceDefectCategory;
            issueType.ServiceDefectCodeText = serviceDefectCodeText;
            issueType.ServiceReasonSchema = serviceReasonSchema;
            issueType.ServiceReasonCategory = serviceReasonCategory;
            issueType.ServiceReasonCodeText = serviceReasonCodeText;
            issueType.ProcessingTimeInHours = processingTimeInHours;
            issueType.Owner = owner;
            issueType.OwnerFullName = ownerFullName;
            issueType.BillToParty = billToParty;
            issueType.ReportedBy = reportedBy;
            issueType.ReportedByFullName = reportedByFullName;
            issueType.ShipToParty = shipToParty;
            issueType.BuildingCustodian = buildingCustodian;
            issueType.CustodianFullName = custodianFullName;
            return issueType;
        }
        /// <summary>
        /// There are no comments for Property ServiceIssue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ServiceIssue")]
        public virtual string ServiceIssue
        {
            get
            {
                return this._ServiceIssue;
            }
            set
            {
                this.OnServiceIssueChanging(value);
                this._ServiceIssue = value;
                this.OnServiceIssueChanged();
                this.OnPropertyChanged("ServiceIssue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ServiceIssue;
        partial void OnServiceIssueChanging(string value);
        partial void OnServiceIssueChanged();
        /// <summary>
        /// There are no comments for Property Priority in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Priority")]
        public virtual string Priority
        {
            get
            {
                return this._Priority;
            }
            set
            {
                this.OnPriorityChanging(value);
                this._Priority = value;
                this.OnPriorityChanged();
                this.OnPropertyChanged("Priority");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Priority;
        partial void OnPriorityChanging(string value);
        partial void OnPriorityChanged();
        /// <summary>
        /// There are no comments for Property PriorityText in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PriorityText")]
        public virtual string PriorityText
        {
            get
            {
                return this._PriorityText;
            }
            set
            {
                this.OnPriorityTextChanging(value);
                this._PriorityText = value;
                this.OnPriorityTextChanged();
                this.OnPropertyChanged("PriorityText");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _PriorityText;
        partial void OnPriorityTextChanging(string value);
        partial void OnPriorityTextChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Description")]
        public virtual string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property ResponsibleEmployee in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ResponsibleEmployee")]
        public virtual string ResponsibleEmployee
        {
            get
            {
                return this._ResponsibleEmployee;
            }
            set
            {
                this.OnResponsibleEmployeeChanging(value);
                this._ResponsibleEmployee = value;
                this.OnResponsibleEmployeeChanged();
                this.OnPropertyChanged("ResponsibleEmployee");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ResponsibleEmployee;
        partial void OnResponsibleEmployeeChanging(string value);
        partial void OnResponsibleEmployeeChanged();
        /// <summary>
        /// There are no comments for Property RespEmployeeFullName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("RespEmployeeFullName")]
        public virtual string RespEmployeeFullName
        {
            get
            {
                return this._RespEmployeeFullName;
            }
            set
            {
                this.OnRespEmployeeFullNameChanging(value);
                this._RespEmployeeFullName = value;
                this.OnRespEmployeeFullNameChanged();
                this.OnPropertyChanged("RespEmployeeFullName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _RespEmployeeFullName;
        partial void OnRespEmployeeFullNameChanging(string value);
        partial void OnRespEmployeeFullNameChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Status")]
        public virtual string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("Status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Status;
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property StatusCriticality in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("StatusCriticality")]
        public virtual byte StatusCriticality
        {
            get
            {
                return this._StatusCriticality;
            }
            set
            {
                this.OnStatusCriticalityChanging(value);
                this._StatusCriticality = value;
                this.OnStatusCriticalityChanged();
                this.OnPropertyChanged("StatusCriticality");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private byte _StatusCriticality;
        partial void OnStatusCriticalityChanging(byte value);
        partial void OnStatusCriticalityChanged();
        /// <summary>
        /// There are no comments for Property StatusText in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("StatusText")]
        public virtual string StatusText
        {
            get
            {
                return this._StatusText;
            }
            set
            {
                this.OnStatusTextChanging(value);
                this._StatusText = value;
                this.OnStatusTextChanged();
                this.OnPropertyChanged("StatusText");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _StatusText;
        partial void OnStatusTextChanging(string value);
        partial void OnStatusTextChanged();
        /// <summary>
        /// There are no comments for Property BusinessActivityCategory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BusinessActivityCategory")]
        public virtual string BusinessActivityCategory
        {
            get
            {
                return this._BusinessActivityCategory;
            }
            set
            {
                this.OnBusinessActivityCategoryChanging(value);
                this._BusinessActivityCategory = value;
                this.OnBusinessActivityCategoryChanged();
                this.OnPropertyChanged("BusinessActivityCategory");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _BusinessActivityCategory;
        partial void OnBusinessActivityCategoryChanging(string value);
        partial void OnBusinessActivityCategoryChanged();
        /// <summary>
        /// There are no comments for Property EntryChannel in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("EntryChannel")]
        public virtual string EntryChannel
        {
            get
            {
                return this._EntryChannel;
            }
            set
            {
                this.OnEntryChannelChanging(value);
                this._EntryChannel = value;
                this.OnEntryChannelChanged();
                this.OnPropertyChanged("EntryChannel");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _EntryChannel;
        partial void OnEntryChannelChanging(string value);
        partial void OnEntryChannelChanged();
        /// <summary>
        /// There are no comments for Property ServiceDefectSchema in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ServiceDefectSchema")]
        public virtual string ServiceDefectSchema
        {
            get
            {
                return this._ServiceDefectSchema;
            }
            set
            {
                this.OnServiceDefectSchemaChanging(value);
                this._ServiceDefectSchema = value;
                this.OnServiceDefectSchemaChanged();
                this.OnPropertyChanged("ServiceDefectSchema");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ServiceDefectSchema;
        partial void OnServiceDefectSchemaChanging(string value);
        partial void OnServiceDefectSchemaChanged();
        /// <summary>
        /// There are no comments for Property ServiceDefectCategory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ServiceDefectCategory")]
        public virtual string ServiceDefectCategory
        {
            get
            {
                return this._ServiceDefectCategory;
            }
            set
            {
                this.OnServiceDefectCategoryChanging(value);
                this._ServiceDefectCategory = value;
                this.OnServiceDefectCategoryChanged();
                this.OnPropertyChanged("ServiceDefectCategory");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ServiceDefectCategory;
        partial void OnServiceDefectCategoryChanging(string value);
        partial void OnServiceDefectCategoryChanged();
        /// <summary>
        /// There are no comments for Property ServiceDefectCodeText in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ServiceDefectCodeText")]
        public virtual string ServiceDefectCodeText
        {
            get
            {
                return this._ServiceDefectCodeText;
            }
            set
            {
                this.OnServiceDefectCodeTextChanging(value);
                this._ServiceDefectCodeText = value;
                this.OnServiceDefectCodeTextChanged();
                this.OnPropertyChanged("ServiceDefectCodeText");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ServiceDefectCodeText;
        partial void OnServiceDefectCodeTextChanging(string value);
        partial void OnServiceDefectCodeTextChanged();
        /// <summary>
        /// There are no comments for Property ServiceReasonSchema in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ServiceReasonSchema")]
        public virtual string ServiceReasonSchema
        {
            get
            {
                return this._ServiceReasonSchema;
            }
            set
            {
                this.OnServiceReasonSchemaChanging(value);
                this._ServiceReasonSchema = value;
                this.OnServiceReasonSchemaChanged();
                this.OnPropertyChanged("ServiceReasonSchema");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ServiceReasonSchema;
        partial void OnServiceReasonSchemaChanging(string value);
        partial void OnServiceReasonSchemaChanged();
        /// <summary>
        /// There are no comments for Property ServiceReasonCategory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ServiceReasonCategory")]
        public virtual string ServiceReasonCategory
        {
            get
            {
                return this._ServiceReasonCategory;
            }
            set
            {
                this.OnServiceReasonCategoryChanging(value);
                this._ServiceReasonCategory = value;
                this.OnServiceReasonCategoryChanged();
                this.OnPropertyChanged("ServiceReasonCategory");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ServiceReasonCategory;
        partial void OnServiceReasonCategoryChanging(string value);
        partial void OnServiceReasonCategoryChanged();
        /// <summary>
        /// There are no comments for Property ServiceReasonCodeText in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ServiceReasonCodeText")]
        public virtual string ServiceReasonCodeText
        {
            get
            {
                return this._ServiceReasonCodeText;
            }
            set
            {
                this.OnServiceReasonCodeTextChanging(value);
                this._ServiceReasonCodeText = value;
                this.OnServiceReasonCodeTextChanged();
                this.OnPropertyChanged("ServiceReasonCodeText");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ServiceReasonCodeText;
        partial void OnServiceReasonCodeTextChanging(string value);
        partial void OnServiceReasonCodeTextChanged();
        /// <summary>
        /// There are no comments for Property ProcessingTimeInHours in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ProcessingTimeInHours")]
        public virtual decimal ProcessingTimeInHours
        {
            get
            {
                return this._ProcessingTimeInHours;
            }
            set
            {
                this.OnProcessingTimeInHoursChanging(value);
                this._ProcessingTimeInHours = value;
                this.OnProcessingTimeInHoursChanged();
                this.OnPropertyChanged("ProcessingTimeInHours");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _ProcessingTimeInHours;
        partial void OnProcessingTimeInHoursChanging(decimal value);
        partial void OnProcessingTimeInHoursChanged();
        /// <summary>
        /// There are no comments for Property Owner in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Owner")]
        public virtual string Owner
        {
            get
            {
                return this._Owner;
            }
            set
            {
                this.OnOwnerChanging(value);
                this._Owner = value;
                this.OnOwnerChanged();
                this.OnPropertyChanged("Owner");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Owner;
        partial void OnOwnerChanging(string value);
        partial void OnOwnerChanged();
        /// <summary>
        /// There are no comments for Property OwnerFullName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("OwnerFullName")]
        public virtual string OwnerFullName
        {
            get
            {
                return this._OwnerFullName;
            }
            set
            {
                this.OnOwnerFullNameChanging(value);
                this._OwnerFullName = value;
                this.OnOwnerFullNameChanged();
                this.OnPropertyChanged("OwnerFullName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _OwnerFullName;
        partial void OnOwnerFullNameChanging(string value);
        partial void OnOwnerFullNameChanged();
        /// <summary>
        /// There are no comments for Property BillToParty in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BillToParty")]
        public virtual string BillToParty
        {
            get
            {
                return this._BillToParty;
            }
            set
            {
                this.OnBillToPartyChanging(value);
                this._BillToParty = value;
                this.OnBillToPartyChanged();
                this.OnPropertyChanged("BillToParty");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _BillToParty;
        partial void OnBillToPartyChanging(string value);
        partial void OnBillToPartyChanged();
        /// <summary>
        /// There are no comments for Property ReportedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ReportedBy")]
        public virtual string ReportedBy
        {
            get
            {
                return this._ReportedBy;
            }
            set
            {
                this.OnReportedByChanging(value);
                this._ReportedBy = value;
                this.OnReportedByChanged();
                this.OnPropertyChanged("ReportedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ReportedBy;
        partial void OnReportedByChanging(string value);
        partial void OnReportedByChanged();
        /// <summary>
        /// There are no comments for Property ReportedByFullName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ReportedByFullName")]
        public virtual string ReportedByFullName
        {
            get
            {
                return this._ReportedByFullName;
            }
            set
            {
                this.OnReportedByFullNameChanging(value);
                this._ReportedByFullName = value;
                this.OnReportedByFullNameChanged();
                this.OnPropertyChanged("ReportedByFullName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ReportedByFullName;
        partial void OnReportedByFullNameChanging(string value);
        partial void OnReportedByFullNameChanged();
        /// <summary>
        /// There are no comments for Property ShipToParty in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipToParty")]
        public virtual string ShipToParty
        {
            get
            {
                return this._ShipToParty;
            }
            set
            {
                this.OnShipToPartyChanging(value);
                this._ShipToParty = value;
                this.OnShipToPartyChanged();
                this.OnPropertyChanged("ShipToParty");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ShipToParty;
        partial void OnShipToPartyChanging(string value);
        partial void OnShipToPartyChanged();
        /// <summary>
        /// There are no comments for Property BuildingCustodian in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BuildingCustodian")]
        public virtual string BuildingCustodian
        {
            get
            {
                return this._BuildingCustodian;
            }
            set
            {
                this.OnBuildingCustodianChanging(value);
                this._BuildingCustodian = value;
                this.OnBuildingCustodianChanged();
                this.OnPropertyChanged("BuildingCustodian");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _BuildingCustodian;
        partial void OnBuildingCustodianChanging(string value);
        partial void OnBuildingCustodianChanged();
        /// <summary>
        /// There are no comments for Property CustodianFullName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CustodianFullName")]
        public virtual string CustodianFullName
        {
            get
            {
                return this._CustodianFullName;
            }
            set
            {
                this.OnCustodianFullNameChanging(value);
                this._CustodianFullName = value;
                this.OnCustodianFullNameChanged();
                this.OnPropertyChanged("CustodianFullName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _CustodianFullName;
        partial void OnCustodianFullNameChanging(string value);
        partial void OnCustodianFullNameChanged();
        /// <summary>
        /// There are no comments for Property ServiceDocCreationDateTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ServiceDocCreationDateTime")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> ServiceDocCreationDateTime
        {
            get
            {
                return this._ServiceDocCreationDateTime;
            }
            set
            {
                this.OnServiceDocCreationDateTimeChanging(value);
                this._ServiceDocCreationDateTime = value;
                this.OnServiceDocCreationDateTimeChanged();
                this.OnPropertyChanged("ServiceDocCreationDateTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _ServiceDocCreationDateTime;
        partial void OnServiceDocCreationDateTimeChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnServiceDocCreationDateTimeChanged();
        /// <summary>
        /// There are no comments for Property CreationDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CreationDate")]
        public virtual global::System.Nullable<global::Microsoft.OData.Edm.Date> CreationDate
        {
            get
            {
                return this._CreationDate;
            }
            set
            {
                this.OnCreationDateChanging(value);
                this._CreationDate = value;
                this.OnCreationDateChanged();
                this.OnPropertyChanged("CreationDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.OData.Edm.Date> _CreationDate;
        partial void OnCreationDateChanging(global::System.Nullable<global::Microsoft.OData.Edm.Date> value);
        partial void OnCreationDateChanged();
        /// <summary>
        /// There are no comments for Property FinishDateTimeStamp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("FinishDateTimeStamp")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> FinishDateTimeStamp
        {
            get
            {
                return this._FinishDateTimeStamp;
            }
            set
            {
                this.OnFinishDateTimeStampChanging(value);
                this._FinishDateTimeStamp = value;
                this.OnFinishDateTimeStampChanged();
                this.OnPropertyChanged("FinishDateTimeStamp");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _FinishDateTimeStamp;
        partial void OnFinishDateTimeStampChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnFinishDateTimeStampChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::Com.Sap.Gateway.Srvd_a2x.Zui_s4crm_sr_zral.V0001.IssueType as global::Com.Sap.Gateway.Srvd_a2x.Zui_s4crm_sr_zral.V0001.IssueTypeSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Com.Sap.Gateway.Srvd_a2x.Zui_s4crm_sr_zral.V0001.IssueTypeSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Com.Sap.Gateway.Srvd_a2x.Zui_s4crm_sr_zral.V0001.IssueType> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Com.Sap.Gateway.Srvd_a2x.Zui_s4crm_sr_zral.V0001.IssueTypeSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Com.Sap.Gateway.Srvd_a2x.Zui_s4crm_sr_zral.V0001.IssueType as global::Com.Sap.Gateway.Srvd_a2x.Zui_s4crm_sr_zral.V0001.IssueTypeSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="serviceIssue">The value of serviceIssue</param>
        public static global::Com.Sap.Gateway.Srvd_a2x.Zui_s4crm_sr_zral.V0001.IssueTypeSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Com.Sap.Gateway.Srvd_a2x.Zui_s4crm_sr_zral.V0001.IssueType> _source,
            string serviceIssue)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "ServiceIssue", serviceIssue }
            };
            return new global::Com.Sap.Gateway.Srvd_a2x.Zui_s4crm_sr_zral.V0001.IssueTypeSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
    }
}
