//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 25.06.2021 08:32:33
namespace Com.Sap.Gateway.Srvd_a2x.Zapi_serviceordertwa.V0001
{
        /// <summary>
        /// There are no comments for Container in the schema.
        /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot) :
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "com.sap.gateway.srvd_a2x.zapi_serviceordertwa.v0001", "Com.Sap.Gateway.Srvd_a2x.Zapi_serviceordertwa.V0001");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("Com.Sap.Gateway.Srvd_a2x.Zapi_serviceordertwa.V0001", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("com.sap.gateway.srvd_a2x.zapi_serviceordertwa.v0001.", originalNameAttribute.OriginalName);
                }
                return string.Concat("com.sap.gateway.srvd_a2x.zapi_serviceordertwa.v0001.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for TWA_Auftrag in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TWA_Auftrag")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<TWA_AuftragType> TWA_Auftrag
        {
            get
            {
                if ((this._TWA_Auftrag == null))
                {
                    this._TWA_Auftrag = base.CreateQuery<TWA_AuftragType>("TWA_Auftrag");
                }
                return this._TWA_Auftrag;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<TWA_AuftragType> _TWA_Auftrag;
        /// <summary>
        /// There are no comments for TWA_Entnahmestellen in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TWA_Entnahmestellen")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<TWA_EntnahmestellenType> TWA_Entnahmestellen
        {
            get
            {
                if ((this._TWA_Entnahmestellen == null))
                {
                    this._TWA_Entnahmestellen = base.CreateQuery<TWA_EntnahmestellenType>("TWA_Entnahmestellen");
                }
                return this._TWA_Entnahmestellen;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<TWA_EntnahmestellenType> _TWA_Entnahmestellen;
        /// <summary>
        /// There are no comments for TWA_Auftrag in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToTWA_Auftrag(TWA_AuftragType tWA_AuftragType)
        {
            base.AddObject("TWA_Auftrag", tWA_AuftragType);
        }
        /// <summary>
        /// There are no comments for TWA_Entnahmestellen in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToTWA_Entnahmestellen(TWA_EntnahmestellenType tWA_EntnahmestellenType)
        {
            base.AddObject("TWA_Entnahmestellen", tWA_EntnahmestellenType);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private const string filePath = @"TwaOrderServiceCsdl.xml";

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader();
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;

                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, true, out edmModel, out errors))
                    {
	                    global::System.Text.StringBuilder errorMessages = new global::System.Text.StringBuilder();
	                    foreach (var error in errors)
	                    {
		                    errorMessages.Append(error.ErrorMessage);
		                    errorMessages.Append("; ");
	                    }
	                    throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader()
            {
                try
                {
                    var assembly = global::System.Reflection.Assembly.GetExecutingAssembly();
                    var resourcePath = global::System.Linq.Enumerable.Single(assembly.GetManifestResourceNames(), str => str.EndsWith(filePath));
                    global::System.IO.Stream stream = assembly.GetManifestResourceStream(resourcePath);
                    return global::System.Xml.XmlReader.Create(new global::System.IO.StreamReader(stream));
                }
                catch(global::System.Xml.XmlException e)
                {
                    throw new global::System.Xml.XmlException("Failed to create an XmlReader from the stream. Check if the resource exists.", e);
                }
            }
        }
    }
        /// <summary>
        /// There are no comments for TWA_EntnahmestellenTypeSingle in the schema.
        /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("TWA_EntnahmestellenTypeSingle")]
    public partial class TWA_EntnahmestellenTypeSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<TWA_EntnahmestellenType>
    {
        /// <summary>
        /// Initialize a new TWA_EntnahmestellenTypeSingle object.
        /// </summary>
        public TWA_EntnahmestellenTypeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new TWA_EntnahmestellenTypeSingle object.
        /// </summary>
        public TWA_EntnahmestellenTypeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new TWA_EntnahmestellenTypeSingle object.
        /// </summary>
        public TWA_EntnahmestellenTypeSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<TWA_EntnahmestellenType> query)
            : base(query) {}

    }
        /// <summary>
        /// There are no comments for TWA_EntnahmestellenType in the schema.
        /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("id")]
    [global::Microsoft.OData.Client.EntitySet("TWA_Entnahmestellen")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("TWA_EntnahmestellenType")]
    public partial class TWA_EntnahmestellenType : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new TWA_EntnahmestellenType object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="entnahmestelle">Initial value of Entnahmestelle.</param>
        /// <param name="zuBeproben">Initial value of ZuBeproben.</param>
        /// <param name="strasseHausnummer">Initial value of StrasseHausnummer.</param>
        /// <param name="etage">Initial value of Etage.</param>
        /// <param name="lageGebaeudeteil">Initial value of LageGebaeudeteil.</param>
        /// <param name="wohnung">Initial value of Wohnung.</param>
        /// <param name="raum">Initial value of Raum.</param>
        /// <param name="genaueEntnahmestelle">Initial value of GenaueEntnahmestelle.</param>
        /// <param name="mieter_id">Initial value of Mieter_id.</param>
        /// <param name="mieter_name">Initial value of Mieter_name.</param>
        /// <param name="mieter_vorname">Initial value of Mieter_vorname.</param>
        /// <param name="mieter_telefon">Initial value of Mieter_telefon.</param>
        /// <param name="mieter_mobile">Initial value of Mieter_mobile.</param>
        /// <param name="mieter_email">Initial value of Mieter_email.</param>
        /// <param name="mieter_abweichendeAdresse">Initial value of Mieter_abweichendeAdresse.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static TWA_EntnahmestellenType CreateTWA_EntnahmestellenType(string ID, 
                    string entnahmestelle, 
                    string zuBeproben, 
                    string strasseHausnummer, 
                    string etage, 
                    string lageGebaeudeteil, 
                    string wohnung, 
                    string raum, 
                    string genaueEntnahmestelle, 
                    string mieter_id, 
                    string mieter_name, 
                    string mieter_vorname, 
                    string mieter_telefon, 
                    string mieter_mobile, 
                    string mieter_email, 
                    string mieter_abweichendeAdresse)
        {
            TWA_EntnahmestellenType tWA_EntnahmestellenType = new TWA_EntnahmestellenType();
            tWA_EntnahmestellenType.Id = ID;
            tWA_EntnahmestellenType.Entnahmestelle = entnahmestelle;
            tWA_EntnahmestellenType.ZuBeproben = zuBeproben;
            tWA_EntnahmestellenType.StrasseHausnummer = strasseHausnummer;
            tWA_EntnahmestellenType.Etage = etage;
            tWA_EntnahmestellenType.LageGebaeudeteil = lageGebaeudeteil;
            tWA_EntnahmestellenType.Wohnung = wohnung;
            tWA_EntnahmestellenType.Raum = raum;
            tWA_EntnahmestellenType.GenaueEntnahmestelle = genaueEntnahmestelle;
            tWA_EntnahmestellenType.Mieter_id = mieter_id;
            tWA_EntnahmestellenType.Mieter_name = mieter_name;
            tWA_EntnahmestellenType.Mieter_vorname = mieter_vorname;
            tWA_EntnahmestellenType.Mieter_telefon = mieter_telefon;
            tWA_EntnahmestellenType.Mieter_mobile = mieter_mobile;
            tWA_EntnahmestellenType.Mieter_email = mieter_email;
            tWA_EntnahmestellenType.Mieter_abweichendeAdresse = mieter_abweichendeAdresse;
            return tWA_EntnahmestellenType;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("id")]
        public virtual string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Entnahmestelle in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("entnahmestelle")]
        public virtual string Entnahmestelle
        {
            get
            {
                return this._Entnahmestelle;
            }
            set
            {
                this.OnEntnahmestelleChanging(value);
                this._Entnahmestelle = value;
                this.OnEntnahmestelleChanged();
                this.OnPropertyChanged("entnahmestelle");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Entnahmestelle;
        partial void OnEntnahmestelleChanging(string value);
        partial void OnEntnahmestelleChanged();
        /// <summary>
        /// There are no comments for Property ZuBeproben in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("zuBeproben")]
        public virtual string ZuBeproben
        {
            get
            {
                return this._ZuBeproben;
            }
            set
            {
                this.OnZuBeprobenChanging(value);
                this._ZuBeproben = value;
                this.OnZuBeprobenChanged();
                this.OnPropertyChanged("zuBeproben");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ZuBeproben;
        partial void OnZuBeprobenChanging(string value);
        partial void OnZuBeprobenChanged();
        /// <summary>
        /// There are no comments for Property StrasseHausnummer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("strasseHausnummer")]
        public virtual string StrasseHausnummer
        {
            get
            {
                return this._StrasseHausnummer;
            }
            set
            {
                this.OnStrasseHausnummerChanging(value);
                this._StrasseHausnummer = value;
                this.OnStrasseHausnummerChanged();
                this.OnPropertyChanged("strasseHausnummer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _StrasseHausnummer;
        partial void OnStrasseHausnummerChanging(string value);
        partial void OnStrasseHausnummerChanged();
        /// <summary>
        /// There are no comments for Property Etage in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("etage")]
        public virtual string Etage
        {
            get
            {
                return this._Etage;
            }
            set
            {
                this.OnEtageChanging(value);
                this._Etage = value;
                this.OnEtageChanged();
                this.OnPropertyChanged("etage");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Etage;
        partial void OnEtageChanging(string value);
        partial void OnEtageChanged();
        /// <summary>
        /// There are no comments for Property LageGebaeudeteil in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("lageGebaeudeteil")]
        public virtual string LageGebaeudeteil
        {
            get
            {
                return this._LageGebaeudeteil;
            }
            set
            {
                this.OnLageGebaeudeteilChanging(value);
                this._LageGebaeudeteil = value;
                this.OnLageGebaeudeteilChanged();
                this.OnPropertyChanged("lageGebaeudeteil");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _LageGebaeudeteil;
        partial void OnLageGebaeudeteilChanging(string value);
        partial void OnLageGebaeudeteilChanged();
        /// <summary>
        /// There are no comments for Property Wohnung in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("wohnung")]
        public virtual string Wohnung
        {
            get
            {
                return this._Wohnung;
            }
            set
            {
                this.OnWohnungChanging(value);
                this._Wohnung = value;
                this.OnWohnungChanged();
                this.OnPropertyChanged("wohnung");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Wohnung;
        partial void OnWohnungChanging(string value);
        partial void OnWohnungChanged();
        /// <summary>
        /// There are no comments for Property Raum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("raum")]
        public virtual string Raum
        {
            get
            {
                return this._Raum;
            }
            set
            {
                this.OnRaumChanging(value);
                this._Raum = value;
                this.OnRaumChanged();
                this.OnPropertyChanged("raum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Raum;
        partial void OnRaumChanging(string value);
        partial void OnRaumChanged();
        /// <summary>
        /// There are no comments for Property GenaueEntnahmestelle in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("genaueEntnahmestelle")]
        public virtual string GenaueEntnahmestelle
        {
            get
            {
                return this._GenaueEntnahmestelle;
            }
            set
            {
                this.OnGenaueEntnahmestelleChanging(value);
                this._GenaueEntnahmestelle = value;
                this.OnGenaueEntnahmestelleChanged();
                this.OnPropertyChanged("genaueEntnahmestelle");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _GenaueEntnahmestelle;
        partial void OnGenaueEntnahmestelleChanging(string value);
        partial void OnGenaueEntnahmestelleChanged();
        /// <summary>
        /// There are no comments for Property Mieter_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("mieter_id")]
        public virtual string Mieter_id
        {
            get
            {
                return this._Mieter_id;
            }
            set
            {
                this.OnMieter_idChanging(value);
                this._Mieter_id = value;
                this.OnMieter_idChanged();
                this.OnPropertyChanged("mieter_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Mieter_id;
        partial void OnMieter_idChanging(string value);
        partial void OnMieter_idChanged();
        /// <summary>
        /// There are no comments for Property Mieter_name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("mieter_name")]
        public virtual string Mieter_name
        {
            get
            {
                return this._Mieter_name;
            }
            set
            {
                this.OnMieter_nameChanging(value);
                this._Mieter_name = value;
                this.OnMieter_nameChanged();
                this.OnPropertyChanged("mieter_name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Mieter_name;
        partial void OnMieter_nameChanging(string value);
        partial void OnMieter_nameChanged();
        /// <summary>
        /// There are no comments for Property Mieter_vorname in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("mieter_vorname")]
        public virtual string Mieter_vorname
        {
            get
            {
                return this._Mieter_vorname;
            }
            set
            {
                this.OnMieter_vornameChanging(value);
                this._Mieter_vorname = value;
                this.OnMieter_vornameChanged();
                this.OnPropertyChanged("mieter_vorname");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Mieter_vorname;
        partial void OnMieter_vornameChanging(string value);
        partial void OnMieter_vornameChanged();
        /// <summary>
        /// There are no comments for Property Mieter_telefon in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("mieter_telefon")]
        public virtual string Mieter_telefon
        {
            get
            {
                return this._Mieter_telefon;
            }
            set
            {
                this.OnMieter_telefonChanging(value);
                this._Mieter_telefon = value;
                this.OnMieter_telefonChanged();
                this.OnPropertyChanged("mieter_telefon");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Mieter_telefon;
        partial void OnMieter_telefonChanging(string value);
        partial void OnMieter_telefonChanged();
        /// <summary>
        /// There are no comments for Property Mieter_mobile in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("mieter_mobile")]
        public virtual string Mieter_mobile
        {
            get
            {
                return this._Mieter_mobile;
            }
            set
            {
                this.OnMieter_mobileChanging(value);
                this._Mieter_mobile = value;
                this.OnMieter_mobileChanged();
                this.OnPropertyChanged("mieter_mobile");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Mieter_mobile;
        partial void OnMieter_mobileChanging(string value);
        partial void OnMieter_mobileChanged();
        /// <summary>
        /// There are no comments for Property Mieter_email in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("mieter_email")]
        public virtual string Mieter_email
        {
            get
            {
                return this._Mieter_email;
            }
            set
            {
                this.OnMieter_emailChanging(value);
                this._Mieter_email = value;
                this.OnMieter_emailChanged();
                this.OnPropertyChanged("mieter_email");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Mieter_email;
        partial void OnMieter_emailChanging(string value);
        partial void OnMieter_emailChanged();
        /// <summary>
        /// There are no comments for Property Mieter_abweichendeAdresse in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("mieter_abweichendeAdresse")]
        public virtual string Mieter_abweichendeAdresse
        {
            get
            {
                return this._Mieter_abweichendeAdresse;
            }
            set
            {
                this.OnMieter_abweichendeAdresseChanging(value);
                this._Mieter_abweichendeAdresse = value;
                this.OnMieter_abweichendeAdresseChanged();
                this.OnPropertyChanged("mieter_abweichendeAdresse");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Mieter_abweichendeAdresse;
        partial void OnMieter_abweichendeAdresseChanging(string value);
        partial void OnMieter_abweichendeAdresseChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
        /// <summary>
        /// There are no comments for TWA_AuftragTypeSingle in the schema.
        /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("TWA_AuftragTypeSingle")]
    public partial class TWA_AuftragTypeSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<TWA_AuftragType>
    {
        /// <summary>
        /// Initialize a new TWA_AuftragTypeSingle object.
        /// </summary>
        public TWA_AuftragTypeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new TWA_AuftragTypeSingle object.
        /// </summary>
        public TWA_AuftragTypeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new TWA_AuftragTypeSingle object.
        /// </summary>
        public TWA_AuftragTypeSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<TWA_AuftragType> query)
            : base(query) {}

    }
        /// <summary>
        /// There are no comments for TWA_AuftragType in the schema.
        /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("id")]
    [global::Microsoft.OData.Client.EntitySet("TWA_Auftrag")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("TWA_AuftragType")]
    public partial class TWA_AuftragType : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new TWA_AuftragType object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="wwaId">Initial value of WwaId.</param>
        /// <param name="wwaStrasseUndHausnummer">Initial value of WwaStrasseUndHausnummer.</param>
        /// <param name="wwaPlz">Initial value of WwaPlz.</param>
        /// <param name="wwaOrt">Initial value of WwaOrt.</param>
        /// <param name="untersuchungspflicht">Initial value of Untersuchungspflicht.</param>
        /// <param name="bemerkungTourenplanung">Initial value of BemerkungTourenplanung.</param>
        /// <param name="gebaeudeNutzung">Initial value of GebaeudeNutzung.</param>
        /// <param name="objektnummer">Initial value of Objektnummer.</param>
        /// <param name="status">Initial value of Status.</param>
        /// <param name="nutzungsarten">Initial value of Nutzungsarten.</param>
        /// <param name="auftragsart">Initial value of Auftragsart.</param>
        /// <param name="stufeNachuntersuchung">Initial value of StufeNachuntersuchung.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static TWA_AuftragType CreateTWA_AuftragType(string ID, 
                    string wwaId, 
                    string wwaStrasseUndHausnummer, 
                    string wwaPlz, 
                    string wwaOrt, 
                    byte untersuchungspflicht, 
                    string bemerkungTourenplanung, 
                    string gebaeudeNutzung, 
                    string objektnummer, 
                    byte status, 
                    string nutzungsarten, 
                    byte auftragsart, 
                    byte stufeNachuntersuchung)
        {
            TWA_AuftragType tWA_AuftragType = new TWA_AuftragType();
            tWA_AuftragType.Id = ID;
            tWA_AuftragType.WwaId = wwaId;
            tWA_AuftragType.WwaStrasseUndHausnummer = wwaStrasseUndHausnummer;
            tWA_AuftragType.WwaPlz = wwaPlz;
            tWA_AuftragType.WwaOrt = wwaOrt;
            tWA_AuftragType.Untersuchungspflicht = untersuchungspflicht;
            tWA_AuftragType.BemerkungTourenplanung = bemerkungTourenplanung;
            tWA_AuftragType.GebaeudeNutzung = gebaeudeNutzung;
            tWA_AuftragType.Objektnummer = objektnummer;
            tWA_AuftragType.Status = status;
            tWA_AuftragType.Nutzungsarten = nutzungsarten;
            tWA_AuftragType.Auftragsart = auftragsart;
            tWA_AuftragType.StufeNachuntersuchung = stufeNachuntersuchung;
            return tWA_AuftragType;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("id")]
        public virtual string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property WwaId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("wwaId")]
        public virtual string WwaId
        {
            get
            {
                return this._WwaId;
            }
            set
            {
                this.OnWwaIdChanging(value);
                this._WwaId = value;
                this.OnWwaIdChanged();
                this.OnPropertyChanged("wwaId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _WwaId;
        partial void OnWwaIdChanging(string value);
        partial void OnWwaIdChanged();
        /// <summary>
        /// There are no comments for Property WwaStrasseUndHausnummer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("wwaStrasseUndHausnummer")]
        public virtual string WwaStrasseUndHausnummer
        {
            get
            {
                return this._WwaStrasseUndHausnummer;
            }
            set
            {
                this.OnWwaStrasseUndHausnummerChanging(value);
                this._WwaStrasseUndHausnummer = value;
                this.OnWwaStrasseUndHausnummerChanged();
                this.OnPropertyChanged("wwaStrasseUndHausnummer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _WwaStrasseUndHausnummer;
        partial void OnWwaStrasseUndHausnummerChanging(string value);
        partial void OnWwaStrasseUndHausnummerChanged();
        /// <summary>
        /// There are no comments for Property WwaPlz in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("wwaPlz")]
        public virtual string WwaPlz
        {
            get
            {
                return this._WwaPlz;
            }
            set
            {
                this.OnWwaPlzChanging(value);
                this._WwaPlz = value;
                this.OnWwaPlzChanged();
                this.OnPropertyChanged("wwaPlz");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _WwaPlz;
        partial void OnWwaPlzChanging(string value);
        partial void OnWwaPlzChanged();
        /// <summary>
        /// There are no comments for Property WwaOrt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("wwaOrt")]
        public virtual string WwaOrt
        {
            get
            {
                return this._WwaOrt;
            }
            set
            {
                this.OnWwaOrtChanging(value);
                this._WwaOrt = value;
                this.OnWwaOrtChanged();
                this.OnPropertyChanged("wwaOrt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _WwaOrt;
        partial void OnWwaOrtChanging(string value);
        partial void OnWwaOrtChanged();
        /// <summary>
        /// There are no comments for Property Untersuchungspflicht in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("untersuchungspflicht")]
        public virtual byte Untersuchungspflicht
        {
            get
            {
                return this._Untersuchungspflicht;
            }
            set
            {
                this.OnUntersuchungspflichtChanging(value);
                this._Untersuchungspflicht = value;
                this.OnUntersuchungspflichtChanged();
                this.OnPropertyChanged("untersuchungspflicht");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private byte _Untersuchungspflicht;
        partial void OnUntersuchungspflichtChanging(byte value);
        partial void OnUntersuchungspflichtChanged();
        /// <summary>
        /// There are no comments for Property BemerkungTourenplanung in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("bemerkungTourenplanung")]
        public virtual string BemerkungTourenplanung
        {
            get
            {
                return this._BemerkungTourenplanung;
            }
            set
            {
                this.OnBemerkungTourenplanungChanging(value);
                this._BemerkungTourenplanung = value;
                this.OnBemerkungTourenplanungChanged();
                this.OnPropertyChanged("bemerkungTourenplanung");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _BemerkungTourenplanung;
        partial void OnBemerkungTourenplanungChanging(string value);
        partial void OnBemerkungTourenplanungChanged();
        /// <summary>
        /// There are no comments for Property GebaeudeNutzung in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("gebaeudeNutzung")]
        public virtual string GebaeudeNutzung
        {
            get
            {
                return this._GebaeudeNutzung;
            }
            set
            {
                this.OnGebaeudeNutzungChanging(value);
                this._GebaeudeNutzung = value;
                this.OnGebaeudeNutzungChanged();
                this.OnPropertyChanged("gebaeudeNutzung");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _GebaeudeNutzung;
        partial void OnGebaeudeNutzungChanging(string value);
        partial void OnGebaeudeNutzungChanged();
        /// <summary>
        /// There are no comments for Property Objektnummer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("objektnummer")]
        public virtual string Objektnummer
        {
            get
            {
                return this._Objektnummer;
            }
            set
            {
                this.OnObjektnummerChanging(value);
                this._Objektnummer = value;
                this.OnObjektnummerChanged();
                this.OnPropertyChanged("objektnummer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Objektnummer;
        partial void OnObjektnummerChanging(string value);
        partial void OnObjektnummerChanged();
        /// <summary>
        /// There are no comments for Property BeprobenBis in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("beprobenBis")]
        public virtual global::System.Nullable<global::Microsoft.OData.Edm.Date> BeprobenBis
        {
            get
            {
                return this._BeprobenBis;
            }
            set
            {
                this.OnBeprobenBisChanging(value);
                this._BeprobenBis = value;
                this.OnBeprobenBisChanged();
                this.OnPropertyChanged("beprobenBis");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.OData.Edm.Date> _BeprobenBis;
        partial void OnBeprobenBisChanging(global::System.Nullable<global::Microsoft.OData.Edm.Date> value);
        partial void OnBeprobenBisChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("status")]
        public virtual byte Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private byte _Status;
        partial void OnStatusChanging(byte value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property Nutzungsarten in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("nutzungsarten")]
        public virtual string Nutzungsarten
        {
            get
            {
                return this._Nutzungsarten;
            }
            set
            {
                this.OnNutzungsartenChanging(value);
                this._Nutzungsarten = value;
                this.OnNutzungsartenChanged();
                this.OnPropertyChanged("nutzungsarten");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Nutzungsarten;
        partial void OnNutzungsartenChanging(string value);
        partial void OnNutzungsartenChanged();
        /// <summary>
        /// There are no comments for Property Auftragsart in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("auftragsart")]
        public virtual byte Auftragsart
        {
            get
            {
                return this._Auftragsart;
            }
            set
            {
                this.OnAuftragsartChanging(value);
                this._Auftragsart = value;
                this.OnAuftragsartChanged();
                this.OnPropertyChanged("auftragsart");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private byte _Auftragsart;
        partial void OnAuftragsartChanging(byte value);
        partial void OnAuftragsartChanged();
        /// <summary>
        /// There are no comments for Property StufeNachuntersuchung in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("stufeNachuntersuchung")]
        public virtual byte StufeNachuntersuchung
        {
            get
            {
                return this._StufeNachuntersuchung;
            }
            set
            {
                this.OnStufeNachuntersuchungChanging(value);
                this._StufeNachuntersuchung = value;
                this.OnStufeNachuntersuchungChanged();
                this.OnPropertyChanged("stufeNachuntersuchung");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private byte _StufeNachuntersuchung;
        partial void OnStufeNachuntersuchungChanging(byte value);
        partial void OnStufeNachuntersuchungChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::Com.Sap.Gateway.Srvd_a2x.Zapi_serviceordertwa.V0001.TWA_EntnahmestellenType as global::Com.Sap.Gateway.Srvd_a2x.Zapi_serviceordertwa.V0001.TWA_EntnahmestellenTypeSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Com.Sap.Gateway.Srvd_a2x.Zapi_serviceordertwa.V0001.TWA_EntnahmestellenTypeSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Com.Sap.Gateway.Srvd_a2x.Zapi_serviceordertwa.V0001.TWA_EntnahmestellenType> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Com.Sap.Gateway.Srvd_a2x.Zapi_serviceordertwa.V0001.TWA_EntnahmestellenTypeSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Com.Sap.Gateway.Srvd_a2x.Zapi_serviceordertwa.V0001.TWA_EntnahmestellenType as global::Com.Sap.Gateway.Srvd_a2x.Zapi_serviceordertwa.V0001.TWA_EntnahmestellenTypeSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Com.Sap.Gateway.Srvd_a2x.Zapi_serviceordertwa.V0001.TWA_EntnahmestellenTypeSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Com.Sap.Gateway.Srvd_a2x.Zapi_serviceordertwa.V0001.TWA_EntnahmestellenType> _source,
            string id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "id", id }
            };
            return new global::Com.Sap.Gateway.Srvd_a2x.Zapi_serviceordertwa.V0001.TWA_EntnahmestellenTypeSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Com.Sap.Gateway.Srvd_a2x.Zapi_serviceordertwa.V0001.TWA_AuftragType as global::Com.Sap.Gateway.Srvd_a2x.Zapi_serviceordertwa.V0001.TWA_AuftragTypeSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Com.Sap.Gateway.Srvd_a2x.Zapi_serviceordertwa.V0001.TWA_AuftragTypeSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Com.Sap.Gateway.Srvd_a2x.Zapi_serviceordertwa.V0001.TWA_AuftragType> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Com.Sap.Gateway.Srvd_a2x.Zapi_serviceordertwa.V0001.TWA_AuftragTypeSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Com.Sap.Gateway.Srvd_a2x.Zapi_serviceordertwa.V0001.TWA_AuftragType as global::Com.Sap.Gateway.Srvd_a2x.Zapi_serviceordertwa.V0001.TWA_AuftragTypeSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Com.Sap.Gateway.Srvd_a2x.Zapi_serviceordertwa.V0001.TWA_AuftragTypeSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Com.Sap.Gateway.Srvd_a2x.Zapi_serviceordertwa.V0001.TWA_AuftragType> _source,
            string id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "id", id }
            };
            return new global::Com.Sap.Gateway.Srvd_a2x.Zapi_serviceordertwa.V0001.TWA_AuftragTypeSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
    }
}
